/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazin.atm_simulator;

import java.awt.HeadlessException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author yazin
 */
public class ATMMainMenu extends javax.swing.JFrame {

    /**
     * This method generates a random account number
     */
    private final ATM atm = new ATM(new Random().nextInt(500) + 500);

    private String generateRandomAccountNumber() {
        String accountNum = "";
        for (int i = 1; i < 11; i++) {
            if (i % 5 == 0) {
                accountNum += "-";
            }
            accountNum += Integer.toString(new Random().nextInt(9));
        }
        return accountNum;
    }

    public ATMMainMenu() {
        initComponents();
        lblAccountNum.setText(generateRandomAccountNumber());
        lblBalance.setText("$" + Integer.toString(atm.getCurrentBalance()));
        lblLastLoginDate.setText(atm.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAccountNum = new javax.swing.JLabel();
        lblLastLoginDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mainPane = new javax.swing.JTabbedPane();
        paneWithdraw = new javax.swing.JPanel();
        btnWithdrawTwenty = new javax.swing.JButton();
        btnWithdrawForty = new javax.swing.JButton();
        btnWithdrawSixty = new javax.swing.JButton();
        btnWithdrawTen = new javax.swing.JButton();
        btnWithdrawFive = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnWithdraw = new javax.swing.JButton();
        withdrawLimitBar = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        lblRemainingWithdrawLimit = new javax.swing.JLabel();
        btnWithdrawFifty = new javax.swing.JButton();
        paneDeposit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnDepositFive = new javax.swing.JButton();
        btnDepositTen = new javax.swing.JButton();
        btnDepositTwenty = new javax.swing.JButton();
        btnDepositForty = new javax.swing.JButton();
        btnDepositFifty = new javax.swing.JButton();
        btnDepositSixty = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        lblRemainingDepositLimit = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        depositLimitBar = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        infoPanel1 = new javax.swing.JPanel();
        lblBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATM Simulator");
        setResizable(false);

        infoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Information"));
        infoPanel.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Account #:");
        jLabel1.setToolTipText("");

        lblAccountNum.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAccountNum.setText("##############");
        lblAccountNum.setToolTipText("");

        lblLastLoginDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLastLoginDate.setText("##############");
        lblLastLoginDate.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Last login date:");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAccountNum))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLastLoginDate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblAccountNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblLastLoginDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        mainPane.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnWithdrawTwenty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawTwenty.setForeground(new java.awt.Color(0, 153, 51));
        btnWithdrawTwenty.setText("$20");
        btnWithdrawTwenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawTwentyActionPerformed(evt);
            }
        });

        btnWithdrawForty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawForty.setForeground(new java.awt.Color(0, 153, 51));
        btnWithdrawForty.setText("$40");
        btnWithdrawForty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawFortyActionPerformed(evt);
            }
        });

        btnWithdrawSixty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawSixty.setForeground(new java.awt.Color(0, 153, 51));
        btnWithdrawSixty.setText("$60");
        btnWithdrawSixty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawSixtyActionPerformed(evt);
            }
        });

        btnWithdrawTen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawTen.setForeground(new java.awt.Color(0, 153, 51));
        btnWithdrawTen.setText("$10");
        btnWithdrawTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawTenActionPerformed(evt);
            }
        });

        btnWithdrawFive.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawFive.setForeground(new java.awt.Color(0, 153, 51));
        btnWithdrawFive.setText("$5");
        btnWithdrawFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawFiveActionPerformed(evt);
            }
        });

        jLabel3.setText("Please choose how much you'd like to withdraw:");
        jLabel3.setToolTipText("");

        btnWithdraw.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdraw.setForeground(new java.awt.Color(0, 153, 51));
        btnWithdraw.setText("Other");
        btnWithdraw.setToolTipText("");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        withdrawLimitBar.setMaximum(750);

        jLabel8.setText("Daily ATM Withdrawal Limit: $750");
        jLabel8.setToolTipText("");

        lblRemainingWithdrawLimit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRemainingWithdrawLimit.setText("(Remaining $750)");
        lblRemainingWithdrawLimit.setToolTipText("");

        btnWithdrawFifty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawFifty.setForeground(new java.awt.Color(0, 153, 51));
        btnWithdrawFifty.setText("$50");
        btnWithdrawFifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawFiftyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneWithdrawLayout = new javax.swing.GroupLayout(paneWithdraw);
        paneWithdraw.setLayout(paneWithdrawLayout);
        paneWithdrawLayout.setHorizontalGroup(
            paneWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneWithdrawLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawLimitBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGroup(paneWithdrawLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRemainingWithdrawLimit))
                    .addGroup(paneWithdrawLayout.createSequentialGroup()
                        .addComponent(btnWithdrawFive, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWithdrawTen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWithdrawTwenty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWithdrawForty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWithdrawFifty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWithdrawSixty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );

        paneWithdrawLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnWithdrawFifty, btnWithdrawFive, btnWithdrawForty, btnWithdrawSixty, btnWithdrawTen, btnWithdrawTwenty});

        paneWithdrawLayout.setVerticalGroup(
            paneWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneWithdrawLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWithdrawTwenty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnWithdrawTen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnWithdrawFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnWithdrawFifty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnWithdrawSixty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnWithdrawForty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(paneWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblRemainingWithdrawLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawLimitBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneWithdrawLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnWithdrawFifty, btnWithdrawFive, btnWithdrawForty, btnWithdrawSixty, btnWithdrawTen, btnWithdrawTwenty});

        mainPane.addTab("Withdraw", paneWithdraw);

        jLabel4.setText("Please choose how much you'd like to deposit:");
        jLabel4.setToolTipText("");

        btnDepositFive.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDepositFive.setForeground(new java.awt.Color(0, 153, 51));
        btnDepositFive.setText("$5");
        btnDepositFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositFiveActionPerformed(evt);
            }
        });

        btnDepositTen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDepositTen.setForeground(new java.awt.Color(0, 153, 51));
        btnDepositTen.setText("$10");
        btnDepositTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositTenActionPerformed(evt);
            }
        });

        btnDepositTwenty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDepositTwenty.setForeground(new java.awt.Color(0, 153, 51));
        btnDepositTwenty.setText("$20");
        btnDepositTwenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositTwentyActionPerformed(evt);
            }
        });

        btnDepositForty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDepositForty.setForeground(new java.awt.Color(0, 153, 51));
        btnDepositForty.setText("$40");
        btnDepositForty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositFortyActionPerformed(evt);
            }
        });

        btnDepositFifty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDepositFifty.setForeground(new java.awt.Color(0, 153, 51));
        btnDepositFifty.setText("$50");
        btnDepositFifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositFiftyActionPerformed(evt);
            }
        });

        btnDepositSixty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDepositSixty.setForeground(new java.awt.Color(0, 153, 51));
        btnDepositSixty.setText("$60");
        btnDepositSixty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositSixtyActionPerformed(evt);
            }
        });

        btnDeposit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeposit.setForeground(new java.awt.Color(0, 153, 51));
        btnDeposit.setText("Other");
        btnDeposit.setToolTipText("");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        lblRemainingDepositLimit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRemainingDepositLimit.setText("(Remaining $2000)");
        lblRemainingDepositLimit.setToolTipText("");

        jLabel9.setText("Daily ATM Withdrawal Limit: $2000");
        jLabel9.setToolTipText("");

        depositLimitBar.setMaximum(2000);

        javax.swing.GroupLayout paneDepositLayout = new javax.swing.GroupLayout(paneDeposit);
        paneDeposit.setLayout(paneDepositLayout);
        paneDepositLayout.setHorizontalGroup(
            paneDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDepositLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositLimitBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGroup(paneDepositLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRemainingDepositLimit))
                    .addGroup(paneDepositLayout.createSequentialGroup()
                        .addComponent(btnDepositFive, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDepositTen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDepositTwenty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDepositForty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDepositFifty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDepositSixty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneDepositLayout.setVerticalGroup(
            paneDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDepositLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDepositTwenty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDepositTen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDepositFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDepositSixty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDepositFifty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDepositForty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(paneDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblRemainingDepositLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositLimitBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPane.addTab("Deposit", paneDeposit);

        jButton1.setText("PRINT RECEIPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        mainPane.addTab("Other Services", jPanel1);

        logTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Transaction Type", "Amount", "Running Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        logTable.getTableHeader().setResizingAllowed(false);
        logTable.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(logTable);

        infoPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Balance"));
        infoPanel1.setEnabled(false);

        lblBalance.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalance.setText("$$$$$");
        lblBalance.setToolTipText("");

        javax.swing.GroupLayout infoPanel1Layout = new javax.swing.GroupLayout(infoPanel1);
        infoPanel1.setLayout(infoPanel1Layout);
        infoPanel1Layout.setHorizontalGroup(
            infoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        infoPanel1Layout.setVerticalGroup(
            infoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atm.printLog(logTable);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDepositFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositFiveActionPerformed
        atm.deposit(5, lblBalance, lblRemainingDepositLimit, logTable, depositLimitBar);
    }//GEN-LAST:event_btnDepositFiveActionPerformed

    private void btnDepositTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositTenActionPerformed
        atm.deposit(10, lblBalance, lblRemainingDepositLimit, logTable, depositLimitBar);
    }//GEN-LAST:event_btnDepositTenActionPerformed

    private void btnDepositTwentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositTwentyActionPerformed
        atm.deposit(20, lblBalance, lblRemainingDepositLimit, logTable, depositLimitBar);
    }//GEN-LAST:event_btnDepositTwentyActionPerformed

    private void btnDepositFortyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositFortyActionPerformed
        atm.deposit(40, lblBalance, lblRemainingDepositLimit, logTable, depositLimitBar);
    }//GEN-LAST:event_btnDepositFortyActionPerformed

    private void btnDepositFiftyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositFiftyActionPerformed
        atm.deposit(50, lblBalance, lblRemainingDepositLimit, logTable, depositLimitBar);
    }//GEN-LAST:event_btnDepositFiftyActionPerformed

    private void btnDepositSixtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositSixtyActionPerformed
        atm.deposit(60, lblBalance, lblRemainingDepositLimit, logTable, depositLimitBar);
    }//GEN-LAST:event_btnDepositSixtyActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        try {
            String input = (String) JOptionPane.showInputDialog(this,
                "Enter the value you would like to deposit:", "Deposit",
                JOptionPane.INFORMATION_MESSAGE, null, null, "1");

            if (input != null) {
                atm.deposit(Integer.parseInt(input.trim()), lblBalance, lblRemainingDepositLimit, logTable, depositLimitBar);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value you have enterned is invalid. Please try again.",
                "Invalid Value", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawFiftyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawFiftyActionPerformed
        atm.withdraw(50, lblBalance, lblRemainingWithdrawLimit, logTable, withdrawLimitBar);
    }//GEN-LAST:event_btnWithdrawFiftyActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        try {
            String input = (String) JOptionPane.showInputDialog(this,
                "Enter the value you would like to withdraw:", "Withdraw",
                JOptionPane.INFORMATION_MESSAGE, null, null, "1");

            if (input != null) {
                atm.deposit(Integer.parseInt(input.trim()), lblBalance, lblRemainingWithdrawLimit, logTable, withdrawLimitBar);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value you have enterned is invalid. Please try again.",
                "Invalid Value", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnWithdrawFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawFiveActionPerformed
        atm.withdraw(5, lblBalance, lblRemainingWithdrawLimit, logTable, withdrawLimitBar);
    }//GEN-LAST:event_btnWithdrawFiveActionPerformed

    private void btnWithdrawTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawTenActionPerformed
        atm.withdraw(10, lblBalance, lblRemainingWithdrawLimit, logTable, withdrawLimitBar);
    }//GEN-LAST:event_btnWithdrawTenActionPerformed

    private void btnWithdrawSixtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawSixtyActionPerformed
        atm.withdraw(60, lblBalance, lblRemainingWithdrawLimit, logTable, withdrawLimitBar);
    }//GEN-LAST:event_btnWithdrawSixtyActionPerformed

    private void btnWithdrawFortyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawFortyActionPerformed
        atm.withdraw(40, lblBalance, lblRemainingWithdrawLimit, logTable, withdrawLimitBar);
    }//GEN-LAST:event_btnWithdrawFortyActionPerformed

    private void btnWithdrawTwentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawTwentyActionPerformed
        atm.withdraw(20, lblBalance, lblRemainingWithdrawLimit, logTable, withdrawLimitBar);
    }//GEN-LAST:event_btnWithdrawTwentyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnDepositFifty;
    private javax.swing.JButton btnDepositFive;
    private javax.swing.JButton btnDepositForty;
    private javax.swing.JButton btnDepositSixty;
    private javax.swing.JButton btnDepositTen;
    private javax.swing.JButton btnDepositTwenty;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btnWithdrawFifty;
    private javax.swing.JButton btnWithdrawFive;
    private javax.swing.JButton btnWithdrawForty;
    private javax.swing.JButton btnWithdrawSixty;
    private javax.swing.JButton btnWithdrawTen;
    private javax.swing.JButton btnWithdrawTwenty;
    private javax.swing.JProgressBar depositLimitBar;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel infoPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccountNum;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblLastLoginDate;
    private javax.swing.JLabel lblRemainingDepositLimit;
    private javax.swing.JLabel lblRemainingWithdrawLimit;
    private javax.swing.JTable logTable;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JPanel paneDeposit;
    private javax.swing.JPanel paneWithdraw;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JProgressBar withdrawLimitBar;
    // End of variables declaration//GEN-END:variables
}
